apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-deployment
  labels:
    app: todo-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
        - name: todo-ui-container
          image: azureuser2211.azurecr.io/todo-ui:latest   # 👈 always fetch latest
          ports:
            - containerPort: 80
      imagePullPolicy: Always   # 👈 ensures cluster pulls latest image
