apiVersion: v1
kind: Service

metadata:
  name: todo-ui-service

spec:
  selector:
    app.kubernetes.io/name: todo-ui

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer